[package]
name = "file-up-down"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.6"
actix-multipart = "0.7.2"
actix-web = "4.9.0"
env_logger = "0.11.5"
futures = "0.3.31"
human_id = "0.1.0"
log = "0.4.22"
